.\" .\" *********************************************************************
.\" .\" *                                                                   *
.\" .\" *             Copyright 2015-2019, Intel Corporation                *
.\" .\" *                                                                   *
.\" .\" *                       All Rights Reserved.                        *
.\" .\" *                                                                   *
.\" .\" *********************************************************************

.TH opa-init-kernel 1 "Intel Corporation" "Copyright(C) 2015\-2019" "IFSFFCLIRG (Man Page)"
.SH NAME
opa-init-kernel


.PP
Initializes the OPA extensions to the RDMA stack. This script is typically run by the system at boot time and is not intended to be run by hand.
.SH Syntax
opa-init-kernel [--help]
.SH Option

.TP 10
--help

Produces full help text.
