.\" .\" *********************************************************************
.\" .\" *                                                                   *
.\" .\" *             Copyright 2015-2019, Intel Corporation                *
.\" .\" *                                                                   *
.\" .\" *                       All Rights Reserved.                        *
.\" .\" *                                                                   *
.\" .\" *********************************************************************

.TH opaautostartconfig 1 "Intel Corporation" "Copyright(C) 2015\-2019" "IFSFFCLIRG (Man Page)"
.SH NAME
opaautostartconfig



.PP
Provides a command line interface to configure autostart options for various OPA utilities.
.SH Syntax

opaautostartconfig --[Action] [Utility]
.SH Options


.TP 10
--help

Produces full help text.

.TP 10
--status

Shows status of setting.

.TP 10
--enable

Enables the setting.

.TP 10
--disable

Disables the setting.

.TP 10
--list

Lists all available utilities.

.TP 10
Utility

Identifies the utility to be acted upon.
