.\" .\" *********************************************************************
.\" .\" *                                                                   *
.\" .\" *             Copyright 2015-2018, Intel Corporation                *
.\" .\" *                                                                   *
.\" .\" *                       All Rights Reserved.                        *
.\" .\" *                                                                   *
.\" .\" *********************************************************************

.TH opaautostartconfig 1 "Intel Corporation" "Copyright(C) 2015\-2018" "Master map: IFSFFCLIRG (Man Page)"
.SH NAME
opaautostartconfig

.PP
Provides a command line interface to configure autostart options for various OPA utilities.
.SH Syntax
opaautostartconfig --[Action] [Utility]
.SH Options

.TP 10
--help
Produces full help text.

.TP 10
--status
Shows status of setting.

.TP 10
--enable
Enables the setting.

.TP 10
--disable
Disables the setting.

.TP 10
--list
Lists all available utilities.

.TP 10
Utility
Available utilities:

.RS

.IP \(bu
HFI\(ulDriver
.IP \(bu
IPOIB
.IP \(bu
SRP
.IP \(bu
SRPT
.IP \(bu
IBACM
.IP \(bu
OPAFM
.IP \(bu
ARPTABLE\(ulTUNE
.IP \(bu
OPA\(ulVNIC

.RE
