.\" .\" *********************************************************************
.\" .\" *                                                                   *
.\" .\" *             Copyright 2015-2019, Intel Corporation                *
.\" .\" *                                                                   *
.\" .\" *                       All Rights Reserved.                        *
.\" .\" *                                                                   *
.\" .\" *********************************************************************

.TH opasystemconfig 1 "Intel Corporation" "Copyright(C) 2015\-2019" "IFSFFCLIRG (Man Page)" 
.SH NAME
opasystemconfig

.NL

.PP
Provides a command line interface to configure system options for various OPA utilities.
.SH Syntax
.NL
opasystemconfig --[Action] [Utility]
.SH Options
.NL

.TP 10
--help 
.NL
Produces full help text.

.TP 10
--status 
.NL
Shows status of setting.

.TP 10
--enable 
.NL
Enables the setting.

.TP 10
--disable 
.NL
Disables the setting.

.TP 10
--list 
.NL
Lists all available utilities.

.TP 10
Utility 
.NL
Identifies the utility to be acted upon.
