#!/bin/sh

set -e

opa-arptbl-tuneup stop

#DEBHELPER#

# Pre-uninstall configuration -- environment variables set by INSTALL script
# Only 0 or 1 value supported; will use default config if set to anything else
if [ "$OPA_INSTALL_CALLER" != "0" ]; then
 if [ "$OPA_UDEV_RULES" != "1" ]; then
   opasystemconfig --disable Udev_Access
 fi
 if [ "$OPA_LIMITS_CONF" != "1" ]; then
   opasystemconfig --disable Memory_Limit
 fi
 if [ "$OPA_ARPTABLE_TUNING" != "1" ]; then
   opaautostartconfig  --disable ARPTABLE_TUNE
 fi
 # modifications to the conf file will not be fixed when the package is reinstalled
 # sed -i -- '/^ARPTABLE_TUNING=[^ ]*/ d' /etc/rdma/rdma.conf

 # SRP and SRPT configs are not currently supported on Debian
 # if [ "$OPA_SRP_LOAD" != "1" ]; then
 #   opaautostartconfig --disable SRP
 # fi
 # if [ "$OPA_SRPT_LOAD" != "1" ]; then
 #   opaautostartconfig --disable SRPT
 # fi
 if [ "$OPA_IRQBALANCE" != "1" ]; then
   opasystemconfig --disable Irq_Balance
 fi
fi


